### PR TITLE
Design changes, jQuery, and WYSIWYG

### PR DESCRIPTION
**Pull request by CosmicWebServices**
This version was not tested unless otherwise noted

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
There seems to be a problem fixing it right now

**Comment by CosmicWebServices** [comment]
It works now one thing I did not try it with the server yet... about to do it

**Comment by CosmicWebServices** [comment]
Wait can someone else do that... Thanks

**Comment by lholliger** [comment]
did you test it? Its not very clear if you did or not

**Comment by haylinmoore** [comment]
Tested

**Comment by jeandrek** [comment]
Buttons don't do anything. I get this error.
```
TypeError: document.getElementById(...).change is not a function
```

**Comment by haylinmoore** [comment]
Ummm I tested with no errors :/

**Comment by haylinmoore** [comment]
But now I get them on live. Reverting PR

**Comment by jeandrek** [comment]
Firefox 54.0.1. Should it be `$('#...').change`?

**Comment by jeandrek** [comment]
The error is at [here](https://github.com/ScratchAT/WhatHaveWeDone/blob/376de6bf5dacb6437ec9835361ba5cc43088a526/index.html#L149).

**Comment by CosmicWebServices** [comment]
Oh lol I know what I did wrong.. change document.getElementById to $()

**Pull request merged**
