### PR TITLE
WYSIWYG + Bootstrap + Jquery fixed version

### PR DESCRIPTION
**Pull request by CosmicWebServices**
Well hopefully testing now :D

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
OK I think the width is broken :(

**Comment by CosmicWebServices** [comment]
Testing again

**Comment by haylinmoore** [comment]
Test Result?

**Comment by CosmicWebServices** [comment]
Good

**Comment by CosmicWebServices** [comment]
As far as I can tell

**Comment by haylinmoore** [comment]
ok

**Comment by haylinmoore** [comment]
pushing, I trust you :P

**Comment by CosmicWebServices** [comment]
OK... That sounds dangerous

**Comment by haylinmoore** [comment]
You got sent to apple headquarters for winning a competition :P I trust you

**Comment by CosmicWebServices** [comment]
Well... alright

**Comment by jeandrek** [comment]
Now there's an error at [this line](https://github.com/CosmicWebServices/WhatHaveWeDone/blob/f307db2a9723ac805c7159cd10ad334743d90e35/index.html#L109).

**Comment by CosmicWebServices** [comment]
Oh my word lol

**Pull request merged**
