### PR TITLE
The best Design and Loading

### PR DESCRIPTION
**Pull request by callowaysutton**
I hope this makes it easier for others to edit

### CODE REVIEW

**Comment by haylinmoore** [comment]
Ummmmm no on the made it faster

**Comment by callowaysutton** [comment]
aw why, I didn't delete anything

**Comment by haylinmoore** [comment]
Because there is no readability :P

**Comment by callowaysutton** [comment]
If only I had the original....

**Comment by haylinmoore** [comment]
Do you mean the thing from the linux source?

**Comment by callowaysutton** [comment]
lol yeah

**Comment by haylinmoore** [comment]
Good I was taking a shot in the dark hoping you had seen that xD

**Comment by callowaysutton** [comment]
hehe it actually does load faster

**Comment by callowaysutton** [comment]
to future peoples wanting to edit: fixmyhtml.com/

**Pull request merged**
